import { Expense, Category } from '../types';

export const DUMMY_EXPENSES: Omit<Expense, 'id'>[] = [
    // --- Current Month ---
    {
        amount: 12.50,
        category: Category.Food,
        date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
        merchant: 'Starbucks',
        notes: 'Morning coffee',
        paymentMethod: 'Credit Card',
        utr: 'UTRSC001',
    },
    {
        amount: 75.00,
        category: Category.Shopping,
        date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
        merchant: 'Amazon',
        notes: 'New keyboard',
        paymentMethod: 'Credit Card',
        utr: 'UTRAMZ001',
    },
    {
        amount: 25.00,
        category: Category.Transport,
        date: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
        merchant: 'Uber',
        notes: 'Trip to the office',
        paymentMethod: 'Google Pay',
        utr: 'UTRUBR001',
    },
    {
        amount: 55.45,
        category: Category.Food,
        date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
        merchant: 'Local Groceries',
        notes: 'Weekly grocery shopping',
        paymentMethod: 'Debit Card',
        utr: 'UTRGroc001',
    },
    {
        amount: 150.00,
        category: Category.BillPayments,
        date: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
        merchant: 'AT&T',
        notes: 'Monthly phone bill',
        paymentMethod: 'Bank Transfer',
        utr: 'UTRATT001',
    },
    {
        amount: 45.00,
        category: Category.Entertainment,
        date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
        merchant: 'AMC Theatres',
        notes: 'Movie night',
        paymentMethod: 'Credit Card',
        utr: 'UTRAMC001',
    },

    // --- Last Month ---
    {
        amount: 8.99,
        category: Category.Entertainment,
        date: new Date(new Date().setMonth(new Date().getMonth() - 1, 28)).toISOString(),
        merchant: 'Netflix',
        notes: 'Subscription',
        paymentMethod: 'Credit Card',
        utr: 'UTRNFLX01',
    },
    {
        amount: 120.75,
        category: Category.Shopping,
        date: new Date(new Date().setMonth(new Date().getMonth() - 1, 25)).toISOString(),
        merchant: 'Zara',
        notes: 'New clothes',
        paymentMethod: 'Credit Card',
        utr: 'UTRZARA01',
    },
    {
        amount: 65.20,
        category: Category.Food,
        date: new Date(new Date().setMonth(new Date().getMonth() - 1, 22)).toISOString(),
        merchant: 'Doordash',
        notes: 'Dinner delivery',
        paymentMethod: 'Google Pay',
        utr: 'UTRDASH01',
    },
    {
        amount: 32.50,
        category: Category.Transport,
        date: new Date(new Date().setMonth(new Date().getMonth() - 1, 18)).toISOString(),
        merchant: 'Gas Station',
        notes: 'Fuel for car',
        paymentMethod: 'Debit Card',
        utr: 'UTRGAS01',
    },
    
    // --- Two Months Ago ---
    {
        amount: 250.00,
        category: Category.Other,
        date: new Date(new Date().setMonth(new Date().getMonth() - 2, 15)).toISOString(),
        merchant: 'IKEA',
        notes: 'New desk chair',
        paymentMethod: 'Credit Card',
        utr: 'UTRIKEA01',
    },
    {
        amount: 95.00,
        category: Category.BillPayments,
        date: new Date(new Date().setMonth(new Date().getMonth() - 2, 10)).toISOString(),
        merchant: 'Comcast',
        notes: 'Internet bill',
        paymentMethod: 'Bank Transfer',
        utr: 'UTRCMCST01',
    },
    {
        amount: 18.50,
        category: Category.Food,
        date: new Date(new Date().setMonth(new Date().getMonth() - 2, 5)).toISOString(),
        merchant: 'Chipotle',
        notes: 'Lunch',
        paymentMethod: 'Credit Card',
        utr: 'UTRCHIP01',
    }
];
